---
- hosts: all
  become: yes
  tasks:
  - name: Ensure NTP (for time sync purposes) is installed.
    yum:
      name: ntp
      state: present

  - name: Ensure NTP is running.
    service:
      name: ntpd
      state: started
      enabled: yes
